### ISSUE TITLE
Update CENNZnut module matching

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#107]
Crate naming convention has changed upstream. It is no longer `srml-`
This should be updated to be more flexible e.g. split on first `-`
https://github.com/cennznet/cennznet/blob/87f52db68909e1eca582f11dab3e74f803edc537/runtime/src/lib.rs#L523

**Comment by roy-powerfinance** [comment]
For internal Tracking: https://centralitydev.atlassian.net/browse/BT-103

**Comment by roy-powerfinance** [comment]
PR is now completed: https://github.com/cennznet/cennznet/pull/108
