### ISSUE TITLE
Revise contract_call_works_without_fee_exchange and contract_call_works_with_fee_exchange tests

### ISSUE THREAD

**Issue by aliXsed** [cennznet/cennznet#157]
The current implementation seems to not control all the factors that would affect the costs of a contract call. After the latest migration of Plug into CENNZnet, they started to show 900 CPAYs and 95 CENNZs extra costs respectively which rendered them fail. We should aim at making them robust to the relevant fees including base, variable, exchange and gas fees.

**Comment by jordy25519** [comment]
closing as stale
