### ISSUE TITLE
Updating previously migrated Sylo vault entries may fail

### ISSUE THREAD

**Issue by aliXsed** [cennznet/cennznet#217]
During the second phase of migrating data between two different chains, we need to update the entries which have changed since the first phase. However, the following check is preventing us from changing a Vault entry if the key for that entry already exists:
https://github.com/cennznet/cennznet/blob/43f355f7ac2866a329e16614a46349ae05e7fa93/crml/sylo/src/vault.rs#L85-L86

**Comment by jordy25519** [comment]
Closed via #218
