### ISSUE TITLE
Random block height stuck

### ISSUE THREAD

**Issue by aliXsed** [cennznet/cennznet#226]
Observed on CENNZnet Azalea 1.0.1, we get full node/validators on which the block height (both the best and the final) stops from growing. The issue seems to happen randomly right at the beginning of a Grandpa Round. In one of the cases, we saw the number of sync peers dropped at the same time and the node kept complaining that:
> verification failed for block ... received from peer ...

In another case, we could catch the following log messages right before the incident:
> import-queue-worker-0 INFO afg  👴 Imported justification for block #808783 that triggers command Changing authorities, signaling voter.
> import-queue-worker-0 INFO afg  Applying authority set change scheduled at block ...
> import-queue-worker-0 INFO sc_finality_grandpa::environment  :older_man: Applying GRANDPA set change to new set 

For both of the cases, a simple restart helped the node to recover from the issue.

**Comment by jordy25519** [comment]
probably safe to close since plug v2 update
