### ISSUE TITLE
Can not build v1.1.0 or latest code on develop branch

### ISSUE THREAD

**Issue by dinhducit** [cennznet/cennznet#265]
I run  ```cargo build --release``` then I got this issue. How can I resolve it?

```
Compiling cennznet-cli v1.1.0 (/home/cennznet/cli)
error: failed to run custom build command for `cennznet-runtime v1.1.0 (/home/cennznet/runtime)`

Caused by:
  process didn't exit successfully: `/home/cennznet/target/release/build/cennznet-runtime-8cf7b9a2b6e7ddd4/build-script-build` (exit code: 1)
  --- stderr
      Updating git repository `https://github.com/plugblockchain/plug-blockchain`
  error: failed to get `substrate-wasm-builder` as a dependency of package `wasm-build-runner-impl v1.0.0 (/home/cennznet/target/release/wbuild-runner/cennznet-runtime9325378180037388287)`

  Caused by:
    failed to load source for dependency `substrate-wasm-builder`

  Caused by:
    Unable to update https://github.com/plugblockchain/plug-blockchain?rev=1.0.0-rc3.1

  Caused by:
    revspec '1.0.0-rc3.1' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by jordy25519** [comment]
Can you share which OS, cargo version, and steps you're using to build?

I can't reproduce on `develop` branch or `1.1.0` (on mac OS Catalina) with `rust 1.45.2`
```
git clone --depth 1 --branch 1.1.0 https://github.com/cennznet/cennznet.git
cd cennznet
cargo build
```

**Comment by dinhducit** [comment]
I using WSL Ubuntu on Windows 10 v2004, cargo version 1.46.0 (149022b1d 2020-07-17)
Steps:
```
git clone https://github.com/cennznet/cennznet.git
cd cennznet
cargo build --release
```

I also had run:
```
rustup install nightly
rustup target add --toolchain=nightly wasm32-unknown-unknown
```


@holygits I have tried follows your steps but I still get this issue on Mac OS Catalina

![image](https://user-images.githubusercontent.com/13290578/92679515-da168c00-f352-11ea-80d3-4678694e6dfe.png)

**Comment by jordy25519** [comment]
@dinhducit should be solved now.
The issues appears with rust 1.46.0, have pushed a fix on the develop branch.
If you'd like to build `1.1.0` please use rustup to switch rust versions to any 1.45.x version

**Comment by dinhducit** [comment]
@holygits yes. it worked.
