### ISSUE TITLE
Sudo token burn & mint

### ISSUE THREAD

**Issue by aliXsed** [cennznet/cennznet#270]
Provide a sudo transaction that when called will:

- Efficiently kill all GA balances on CENNZnet
- Mint some given GA balances
- Kill or adjust any GA balance metadata accurately e.g. total issuance, locks, and the staking ledger bonded amounts etc. should be updated also.

**Motivation**: This will be the precursor operation to ensure all CENNZ/CPAY issuance on CENNZnet is according to the original ERC-20 based issuance. When executed it will allow us to bootstrap the CENNZnet development fund based on ERC-20 issuance and distribute CENNZ to Centrality validators and CPAY to Sudo + Sylo account etc. accordingly

**Comment by jordy25519** [comment]
all done!
