### ISSUE TITLE
Re-enable staking module critical extrinsics

### ISSUE THREAD

**Issue by aliXsed** [cennznet/cennznet#297]
This issue is generated for future work. CENNZnet staking will be initially limited and the extrinsic calls such as `bond`, `bond_extra`, `unbond`, `rebond`, `withdraw_unbonded` will not be publicly available. However, according to CENNZnet roadmap, we will re-enable them fully for the general public soon after CENNZnet public release.

**Comment by jordy25519** [comment]
I think we made this configurable on chain so this can be closed

**Comment by aliXsed** [comment]
@holygits Would we want to keep it configurable even after we have the critical functions re-enabled?
