### ISSUE TITLE
staking.currentEraReward() omits the transaction fee in last session of era

### ISSUE THREAD

**Issue by xfylsj** [cennznet/cennznet#30]
Just found the api `staking.currentEraReward()` did not calculate the transaction fee from the last session of an era.
As I know, the session tx fee will be added to era reward at next session, but for the last session, its next session is a new era, and the era reward will be reset to 0. Maybe  that's why the tx fee of last session is omitted.

**Comment by jordy25519** [comment]
solved by #232
