### ISSUE TITLE
deposit Fees.Charged event in Apply stage

### ISSUE THREAD

**Issue by ianhe8x** [cennznet/cennznet#37]
Currently Fees.Charged event is deposited in block finalized stage, extrinsic_idx is included as event data, which prevent it be passed in extrinsic send's callback.

**Comment by holygits** [comment]
Does this need to be moved to https://github.com/cennznet/plug-blockchain?

**Comment by xlc** [comment]
For this stage we will have a `Charged` event and optionally `Refunded` event and both are emitted when the action is performed (i.e. during apply phase instead finalize phase)

**Comment by xlc** [comment]
Should do this after #53 
And depends on https://github.com/paritytech/substrate/issues/3227 https://github.com/cennznet/substrate/tree/post-dispatch
Fees module should implement `SignedExtension` and charge fee in `pre_dispatch`, optional refund fee in `dispatch` (by calling `ChargeFee::refund_fee`) and emit event in `post_dispatch` with final charged amount.

**Comment by jordy25519** [comment]
Invalid
