### ISSUE TITLE
Re-enable ignored staking module tests

### ISSUE THREAD

**Issue by aliXsed** [cennznet/cennznet#389]
The staking module of cennznet runtime version 40, will soon undergo an upgrade. So due to the anticiptaion of that upgrade, some of the related tests that are failing as side-effects of updating to plug 3.0 will be ignored and a TODO with this issue number will mark them. This is a reminder for us to re-enable and fix those tests after upgrading the staking module.

**Comment by jordy25519** [comment]
can this be closed @aliXsed ?

**Comment by aliXsed** [comment]
> can this be closed @aliXsed ?

Yes.
