### ISSUE TITLE
NFT semi-fungibles support

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#437]
Helpful to have batch methods to reduce cost and better API ergonomics
- [x] batch create tokens
- [x] batch fixed price sales (cc #434)
- [x] batch auctions (cc #434)
- [x] batch transfer tokens

**Comment by miketamis** [comment]
Heres what I'm thinking, we make it so that every NFT has a unique identifier from every other NFT (even outside its collection). Collections are a NFT prototype, (for everything, metaurl, royalties, etc). This means that you can operate on an NFT with just its TokenId.

```
CollectionOwner: CollectionId => Option<AccountId>
Balances: (TokenId, AccountId) => Balance
TokenCollection: TokenId => CollectionId
CollectionTokens: (CollectionId, TokenId) => ()
TokenAttributes: (TokenId) => Vec<NFTAttributeValue>
```

**Comment by jordy25519** [comment]
Yeah this makes alot of sense. Splitting the collection and token id definitely created some problems for semi-fungible support

this will use the hash of `(CollectionId, TokenId)` as the key which would be unique in the module:
`Balances: ((CollectionId, TokenId), AccountId) => Balance`
