### ISSUE TITLE
NFT metadata URI standards 

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#442]
Define a standard for constructing token metadata URIs depending on the base URI protocol
Building on https://eips.ethereum.org/EIPS/eip-1155#metadata

1) if collection base URI is `http(s)://`
format: `${collectionUri}/${tokenId}` without `0x` prefix
example: `nft.example.com/8e31838a80773cf4c25053051f651acd5c8d0184f3194b3e99804da5162fec0f`
`MetadataCID` is optional at token creation

2) if collection base URI is `ipfs://`
format: `${collectionUri}/${MetadataCID}`
example: `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi`
`MetadataCID` must be given at token creation
where `MetadataCID` is the CID of the `metadata.json` object on IPFS

3) Similar to 2) but for Arweave stored

Module would add a storage
`TokenMetadataCID: map  TokenId -> Option<Vec<u8>>`

Module could define an RPC method to construct this for clients
`api.rpc.nft.tokenMetadataUri(tokenId)` similar to ERC1155

Makes sense to make a new attribute type `CID` to support this

**Comment by dhjjjer** [comment]
Hey, man! May you explain can I upload metadata to this smart contract? https://etherscan.io/address/0xe77da975fb81e7ae50a89be981e60d31e4387a29#code

**Comment by JasonTulp** [comment]
> Hey, man! May you explain can I upload metadata to this smart contract? https://etherscan.io/address/0xe77da975fb81e7ae50a89be981e60d31e4387a29#code

Hi dhjjjer, on Ethereum metadata is handled by each marketplace, such as OpenSea through custom API endpoints. [Opensea Metadata Standards](https://docs.opensea.io/docs/metadata-standards) This process is a whole lot easier on CENNZnet as you can define metadata as attributes when you mint an NFT [Minting an NFT on CENNZnet](https://wiki.cennz.net/#/CENNZnet-API/NFT-API?id=minting-an-nft)

**Comment by jordy25519** [comment]
## Metadata Schemes
When creating an NFT series a metadata scheme must be provided.
Initially there will be two supported schemes.

## 1) HTTP(S)
An HTTP API provides a JSON document given a valid serial number from the series.
`https://<host>/<path>+/<serialNumber>`

e.g. `https://api.example.com/tokens/123`

## 2) IPFS directory
The entire series metadata should be known beforehand and uploaded as an IPFS directory.
The metadata files in the directory should be named according to their serial numbers.
```console
metadata
├── 0.json
├── 1.json
├── 2.json
└── 3.json
```

e.g. `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/123.json` returns the metadata JSON document for token with serial number `123`

## 3) Unique IPFS /AR files
This is a 3rd option but will require the series creator to upload individual CIDs/file hashes with each token. This option will not be implemented initially for simplicity sake.

**Comment by jordy25519** [comment]
recorded here: https://wiki.cennz.net/#/Dapp-development/Guides/NFT-metadata-standard?id=metadata-reference-scheme
