### ISSUE TITLE
ERC20 precompile

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#509]
Provide ERC20 precompile for generic assets allowing them to appear in metamask/ethereum wallets & interoperate with EVM contracts on CENNZnet

example here: https://github.com/PureStake/moonbeam/blob/master/precompiles/assets-erc20/src/lib.rs

**Comment by jordy25519** [comment]
the approvals interfaces are dependent on #575

**Comment by xdexterman** [comment]
Noted. Will take over this issue
