### ISSUE TITLE
Rewrite FeeExchange using Extensible transactions

### ISSUE THREAD

**Issue by xlc** [cennznet/cennznet#52]
The new extrinsic structure in Plug 1.0 requires `FeeExchange` logic be re-written using the `SignedExtension` trait and it's provided hooks.

Example impl can be found in srml/system e.g. `CheckWeight` https://github.com/plugblockchain/plug-blockchain/blob/e57ff013d33197899807aab94793ffbb575b0562/srml/system/src/lib.rs#L931

`FeeExchange` allows users to use CENNZX to seamlessly pay for transaction fees any currency/asset given it has liquidity in the exchange.

Tasks:
Rewrite FeeExchange logic with SignedExtension trait implementation
- [ ] Add `Option<FeeExchange<Balance>>` to SignedExtra payload (replaces https://github.com/cennznet/cennznet/blob/ec299bfb0d5230ac2388ef021ee129205f8b8d4a/primitives/src/cennznet_extrinsic.rs#L48)

- [ ] Re-implement BuyFeeAsset trait
https://github.com/cennznet/cennznet/blob/ec299bfb0d5230ac2388ef021ee129205f8b8d4a/prml/fees/src/lib.rs#L76-L88
https://github.com/cennznet/cennznet/blob/ec299bfb0d5230ac2388ef021ee129205f8b8d4a/crml/cennzx-spot/src/impls.rs#L52-L70

- [ ] Use BuyFeeAsset with provided SignedExtension hooks
Replaces: https://github.com/cennznet/cennznet/blob/ec299bfb0d5230ac2388ef021ee129205f8b8d4a/runtime/src/fee.rs#L44-L46

**Comment by jordy25519** [comment]
Closing for refinement
