### ISSUE TITLE
EVM support

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#567]
Integrate frontier's pallet-ethereum and pallet-evm

TODO:
- [x] support fee tooling assuming 18dp wei inputs (i.e. conversion to CPAY 4dp value)
- [x] define Eth to CENNZ address mappings
1) it must match `eth-wallet` pallet)
2) it should be reversible so that contracts can compare 20 byte address with CENNZnet native 32 byte address and vice versa
this function will needs a js counterpart `utilCrypto.evmToAddress` will not match any longer

Next:
- [x] erc721 precompile for nfts #505
- [x] erc20 precompile for ga #509
- [x] block author address mapping (ensure validator can retrieve rewards)
- [x] add geth block explorer endpoints `txpool_content`
~- [ ] Add chainId `3000` for CENNZnet at https://chainlist.org/~
this service is to be discontinued

Other:

configuring base fee and elasticity is required for rollout
```
api.tx.baseFee.setBaseFeePerGas('5500000000000')
api.tx.baseFee.setElasticity(100)
```

**Comment by xdexterman** [comment]
Hi @holygits , Jerry and Leo  let me help out on this issue. Just quick check on that which part of the TODOs I can help with?

**Comment by jordy25519** [comment]
hi @xdexterman,
#509 would be a good issue to take on, you can PR to this branch: `spike/evm-support`
also lmk via slack or discord if you want to talk about the issue some more
