### ISSUE TITLE
Use substrate support of large integers for CENNZX and refine calculations

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#59]
tracker for: https://github.com/cennznet/cennznet/blob/ec299bfb0d5230ac2388ef021ee129205f8b8d4a/crml/cennzx-spot/src/lib.rs#L37

arithmetic crate: https://github.com/plugblockchain/plug-blockchain/tree/1.0.0-rc1/core/sr-arithmetic

Depends on: #60

**Comment by aliXsed** [comment]
Would you please clarify which types you expect to be affected? So far the only type I could find replaceable is 
U256 -> arithmetic::biguint::BigUint
I create a PR based on this assumption just in case it's really the only change we need for this issue.

**Comment by aliXsed** [comment]
Actually I realized our very high-performance option for U256 is when we use Substrate with the x64_arithmetic feature flag and then import it from bigint::uint. The other option is importing U256 from substrate_primitives::uint::U256 and not the arithmetic module. What I haven't yet come across or didn't notice is the use of rational numbers in CENNZX. Can you please point me to a place in the code?
