### ISSUE TITLE
Migrate rewards to Plug 1.0

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#61]
Update the `crml/rewards` crate dependencies to`https://github.com/plugblockchain/plug-blockchain` and `branch = 1.0.0-rc1`

- [ ] Add the module back into the runtime defintion

**Comment by mzxyz** [comment]
Subissues need to be resolved:

- [ ] `CurrentEraReward` in staking module has been removed, will figure out whether we still need this to be updated

- [ ] Dependency on `fee module`
```rust
impl<T: Trait> OnFeeCharged<AmountOf<T>> for Module<T> {
	fn on_fee_charged(fee: &AmountOf<T>) {
		<SessionTransactionFee<T>>::mutate(|current| *current += *fee);
	}
}
```

**Comment by jordy25519** [comment]
Parking, until further refinement
