### ISSUE TITLE
Offline sensitivity

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#621]
Due to CENNZnet's fast session time (120 blocks) it is (potentially over) sensitive to offline reports.
Polkadot requires online reports once every hour.

Take some measures to reduce the sensitivity of this check or improve the robustness of the reporting

cc #385 which touches on this from the POV of increasing the session length.

**Comment by jordy25519** [comment]
resolved since 2.1.0 update, no unexpected offline reports

**Comment by downlikedefi** [comment]
hey, how often are offline checks done now?

**Comment by jordy25519** [comment]
@downlikedefi its still checked once per session ~120blocks/10minutes

the way its reported is more robust now due to this upstream change (https://github.com/paritytech/substrate/pull/8819/files) which landed in the 2.1.0 update.

we can reopen this issue if we find there's still unexpected offline reports
