### ISSUE TITLE
Enable multi-currency gas payments in EVM

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#627]
`EthereumTransaction`s follow a different path to validation and fee payment vs. native transactions so are missing this ability

`OnChargeTransaction::withdraw_fee` can do the swap but still need a way to access and pass the fee preferences from the caller

Ideas
---
- User can set fee preferences via a one time config tx. withdraw_fee will access this storage to figure out fee currency. (setup can be annoying, existing ethereum tooling is not aware of the config)

**Comment by JasonTulp** [comment]
Main PR: #630

**Comment by JasonTulp** [comment]
Precompiles PR: #631
