### ISSUE TITLE
Update main.rs to rust 2018

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#65]
https://github.com/cennznet/cennznet/blob/develop/src/main.rs
- [ ] Remove `extern crate`s
- [ ] Move package aliasing into Cargo.toml and make naming consistent with other crates e.g. `substrate-primitives` -> `primitives`, `sr-primitives` -> `sr_primitives`

**Comment by mzxyz** [comment]
Would like to take this as next task
