### ISSUE TITLE
Plug 1.0 Upgrade - Runtime Setup

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#66]
Prepare the CENNZnet node runtime definition for further 1.0 upgrade work.

Tasks:

-  [x] Remove `crml` and `prml` Modules from the node runtime definition.
These crates may be added back into the runtime definition when they are individually upgraded.

https://github.com/cennznet/cennznet/blob/ec299bfb0d5230ac2388ef021ee129205f8b8d4a/runtime/src/lib.rs#L251-L284

- [ ] The runtime extrinsic types should be changed to `sr_primitives::UncheckedExtrinsic` and `sr_primitives::CheckedExtrinsic` and `SignedExtra`payload added

https://github.com/plugblockchain/plug-blockchain/blob/2c18dfb984df5f4c42adfb8fc734fea91df6a38b/node/runtime/src/lib.rs#L543-L560

A/C - It compiles (Tests will be fixed on a per crate basis)

**Comment by cowboy-bebug** [comment]
The work is being done in this [branch](https://github.com/cennznet/cennznet/tree/plug-1.0). A couple more things to be added:
- [ ] `src/` - entrypoint
- [ ] `genesis/` - might also be required for the above entrypoint

**Comment by jordy25519** [comment]
Can use the genesis from plug initially. Can be reconfigured later
