### ISSUE TITLE
ETH deposit on rata/Ropsten fails with erc20Peg.DelayedErc20DepositFailed error

### ISSUE THREAD

**Issue by KarishmaBothara** [cennznet/cennznet#673]
This particular transaction on Ropsten bridge fails when trying to deposit the claim on CENNZnet side - https://ropsten.etherscan.io/tx/0xcb25af02a5e6cac48ba7aa1d9ebf1a2b1094d282c10e84bab754e1106700bec3
There is 0.00000001 Ether associated with this txs... It works on local but fails on rata - 
https://rata.uncoverexplorer.com/block/3760077
Cloud watch doesn't show any match for 'mismatch in provided data vs. observed data' on rata

---

details from validator notarization
```log
2022-06-09 22:48:51.297 TRACE      offchain-worker eth-bridge: 💎 mismatch in provided data vs. observed data. provided: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 165, 169, 188, 129, 241, 14, 178, 236, 127, 136, 30, 103, 48, 213, 189, 90, 138, 137, 62, 166, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, │
│  0, 0, 0, 0, 0, 0, 0, 3, 232, 99, 118, 109, 58, 0, 0, 0, 0, 0, 0, 0, 68, 140, 142, 158, 24, 22, 48, 13, 208, 82, 231, 125, 42, 68, 201, 144, 162, 128, 125, 21, 204] observed: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 165, 169, 188, 129, 241, 14, 178, 236, 127, 136, 30, 103, 48, 213, 189, 90, 138, 137, 62, 166, 0, 0, 0, 0, 0, │
│  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 54, 53, 201, 173, 197, 222, 160, 0, 0, 99, 118, 109, 58, 0, 0, 0, 0, 0, 0, 0, 68, 140, 142, 158, 24, 22, 48, 13, 208, 82, 231, 125, 42, 68, 201, 144, 162, 128, 125, 21, 204] 
```

**Comment by jordy25519** [comment]
@KarishmaBothara which version was used to test locally?

**Comment by KarishmaBothara** [comment]
cennznet/cennznet:latest

**Comment by jordy25519** [comment]
wrong amount used in the deposit claim

bad claim: https://rata.uncoverexplorer.com/extrinsic/3760076-1
good claim: https://rata.uncoverexplorer.com/extrinsic/3808662-1
