### ISSUE TITLE
Smart Contract to support Multi Token

### ISSUE THREAD

**Issue by bette7** [cennznet/cennznet#7]
CENNZNet is designed to be a multi-token chain to support its economic model and its dApp community. At a very high level, CENNZNet public mainnet will have CENNZ as staking token, CPay as spending token which is used for paying transaction fees, and minted as reward to validators. It also supports multiple reserve tokens for protocol level dApps such as SYLO and CERTI who build from runtime modules. 

While multi-token support is a must-have intrinsic chain feature for our community, we strive to align with upstream codebase and development roadmap to support the larger substrate community. 
So far we have a working multi-token implementation, by adding generic asset and reward module, and modifying balance and staking modules etc. 

We now come to a point to enable our community to develop Smart Contract with multi-token support. Below are a couple options from @xlc for consideration:

**Comment by xlc** [comment]
I see three paths forwards:

1. Have Substrate natively supports multi token model. This means contract module will have multi token model support as well.
Requires upstream collaboration.
Work required:  ★★★★★
Maintenance cost:  ★☆☆☆☆
Related issue: https://github.com/cennznet/plug-blockchain/issues/5 
2. Fork contract module and Ink! to modify balance query / sending method to add `AssetId` as an additional parameter. This means we need to maintain a long term fork for both projects. 
Work required:  ★★★☆☆
Maintenance cost:  ★★★★☆
3. Make minimal upstream contract module change, make some claver type as the `Balance` type somehow make multi currency possible in a single currency system.
Work required:  ★★★★★
Maintenance cost:  ★★★☆☆
Likely to encounter some major blocker make this impossible.
Related discussion: https://github.com/paritytech/substrate/pull/2205

**Comment by xlc** [comment]
We will pick No. 2.

Continue on https://github.com/cennznet/plug-blockchain/issues/13
