### ISSUE TITLE
Modified crml/transaction-payment

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#86]
Introduce the transaction payment module into the CENNZnet runtime modules library (crml).
It will be modified to support the special fee payment logic required in CENNZnet.

Tasks:
- [x] Create a git subtree `crml/transaction-payment` from plug `srml/transaction-payment`

- [ ] Add an associated `AssetId` type to the module's Trait, like GA has e.g.
https://github.com/plugblockchain/plug-blockchain/blob/b93e3585eb9bb9f1648a0d155e67832a8aa7f30c/srml/generic-asset/src/lib.rs#L188

- [x]  Change `SignedExtra` and the runtime definition to use this module instead of the plug module.
Re-directing the Cargo dependency should be enough https://github.com/cennznet/cennznet/blob/db9168cf47c56afee001f9aa2e7796c4fe0fce62/runtime/Cargo.toml#L57

**Comment by hoani** [comment]
Discussed `AssetId` with @holygits, will integrate `AssetId` into the modules' trait when it is needed in #88
